name: CI

on: [push]

jobs:
  build:

    runs-on: node:latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: yarn install
    - name: Run a multi-line script
      run: |
        yarn --version
        yarn install
